/**
 * lib/device/releaseManifest.js
 *
 * Single source of truth for the current SAMS Device Agent release metadata.
 *
 * Used by:
 *   - app/login/page.jsx          — "Not Installed" screen download button
 *   - components/devices/DeviceDownloads.jsx  — Downloads tab in Device Maintenance
 *
 * How to update for a new release:
 *   1. Build the installer:  cd sams-agent/installer && .\build-installer.ps1
 *   2. Host the output .exe at a stable URL (e.g. /downloads/ on your server)
 *   3. Update CURRENT_RELEASE below with the new version, date, SHA-256, and URL
 *   4. Add the previous release to VERSION_HISTORY
 */

export const CURRENT_RELEASE = {
  /** Semver string — must match the value in SAMSAgent.csproj <Version>. */
  version: '1.0.0',

  /** ISO 8601 release date. */
  releaseDate: '2026-08-01',

  /**
   * File size of the installer exe (human-readable string).
   * Update this after building. Run:
   *   (Get-Item SAMSAgentSetup-1.0.0.exe).Length / 1MB  → "42.3 MB"
   */
  fileSize: null,   // e.g. '42.3 MB' — set after build

  /**
   * SHA-256 hex hash of the installer exe (lowercase, 64 chars).
   * Generated by build-installer.ps1 and written to installer/output/release.json.
   * Run manually: Get-FileHash SAMSAgentSetup-1.0.0.exe -Algorithm SHA256
   */
  sha256: null,   // e.g. 'a3f2c9d1...' — set after build

  /**
   * Public download URL for the installer exe.
   * null = download button is disabled with "unavailable" message.
   * Example: '/downloads/SAMSAgentSetup-1.0.0.exe'
   */
  downloadUrl: null,

  /** What changed in this release. */
  releaseNotes: [
    'Initial release of the SAMS Device Agent.',
    'Hardware fingerprint generated from BIOS UUID, motherboard serial, CPU ID, disk serial, MAC address, TPM version, machine GUID, and computer name.',
    'Exposes GET /health and GET /device on localhost:48763.',
    'Automatic device registration and approval workflow via the SAMS backend.',
    'Installs as a Windows Service with automatic startup.',
    'Structured logging to Windows Event Log and console.',
  ],
};

export const VERSION_HISTORY = [
  {
    version:     '1.0.0',
    releaseDate: '2026-08-01',
    notes:       'Initial release.',
  },
];
