services:
  mongodb:
    image: mongo:7
    container_name: smas-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: smas
