/**
 * Attendance History Excel Export using ExcelJS
 * Generates an Excel workbook with role, date range, labour type, and unit filters.
 */

function triggerBlobDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

function safeFilename(str) {
  return String(str || '')
    .trim()
    .replace(/[^\w\-.]+/g, '_')
    .slice(0, 50);
}

function toDateStr(d) {
  if (!d) return '';
  if (typeof d === 'string') return d;
  if (typeof d === 'object') {
    if (typeof d.date === 'string') return d.date;
    if (d instanceof Date && !isNaN(d.getTime())) return d.toISOString().split('T')[0];
  }
  return String(d || '');
}

function formatDateDisplay(isoDateStr) {
  const dateStr = toDateStr(isoDateStr);
  if (!dateStr) return '';
  const parts = dateStr.split('-');
  if (parts.length === 3) {
    return `${parts[2]}/${parts[1]}/${parts[0]}`;
  }
  return dateStr;
}

function dayOfWeekName(isoDateStr) {
  const dateStr = toDateStr(isoDateStr);
  if (!dateStr) return '';
  const days = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'];
  const d = new Date(`${dateStr}T12:00:00.000Z`);
  return isNaN(d.getTime()) ? '' : (days[d.getUTCDay()] || '');
}

function getAttendanceCode(day) {
  if (!day || day.status === 'blank') return '—';
  if (day.status === 'A') return 'A';
  if (day.code === 'DS') return 'DS';
  if (day.code === '1.5S' || day.code === '1.5') return '1.5S';
  if (day.status === 'HD') return day.code || 'HD';
  if (day.status === 'FH' || day.status === 'SH') return day.code || day.status;
  if (day.status === 'PT') return 'PT';
  if (day.status === 'P') {
    if (day.code === 'DS') return 'DS';
    if (day.code === '1.5S' || day.code === '1.5') return '1.5S';
    return 'P';
  }
  return day.code === 'OT' ? 'P' : (day.code || day.status || 'P');
}

export async function downloadAttendanceHistoryExcel(gridData, {
  roleName = '',
  dateFrom = '',
  dateTo = '',
  labourType = '',
  divisionNames = [],
  generatedBy = '',
} = {}) {
  const ExcelJS = (await import('exceljs')).default;
  const wb = new ExcelJS.Workbook();
  wb.creator = 'SAMS';
  wb.created = new Date();

  const ws = wb.addWorksheet('Attendance History', {
    views: [{ state: 'frozen', xSplit: 3, ySplit: 8 }],
  });

  // ─── 1. Title & Meta Block ──────────────────────────────────────────
  ws.mergeCells('A1:G1');
  const titleCell = ws.getCell('A1');
  titleCell.value = 'SAMS — Attendance History Report';
  titleCell.font = { bold: true, size: 16, color: { argb: 'FF1E293B' } };
  titleCell.alignment = { vertical: 'middle' };
  ws.getRow(1).height = 28;

  ws.getCell('A2').value = 'Smart Access Management System';
  ws.getCell('A2').font = { italic: true, size: 10, color: { argb: 'FF64748B' } };

  const metaRows = [
    ['Role', roleName || 'All Roles', '', 'Period', `${formatDateDisplay(dateFrom)} to ${formatDateDisplay(dateTo)}`],
    ['Units / Divisions', divisionNames.length > 0 ? divisionNames.join(', ') : 'All Units', '', 'Labour Type', labourType || 'All'],
    ['Generated On', new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }), '', 'Generated By', generatedBy || 'Administrator'],
  ];

  let metaRowIdx = 4;
  for (const row of metaRows) {
    ws.getCell(`A${metaRowIdx}`).value = row[0];
    ws.getCell(`A${metaRowIdx}`).font = { bold: true, size: 9, color: { argb: 'FF475569' } };
    ws.getCell(`B${metaRowIdx}`).value = row[1];
    ws.getCell(`B${metaRowIdx}`).font = { size: 9 };

    ws.getCell(`D${metaRowIdx}`).value = row[3];
    ws.getCell(`D${metaRowIdx}`).font = { bold: true, size: 9, color: { argb: 'FF475569' } };
    ws.getCell(`E${metaRowIdx}`).value = row[4];
    ws.getCell(`E${metaRowIdx}`).font = { size: 9 };
    metaRowIdx += 1;
  }

  // ─── 2. Table Headers ───────────────────────────────────────────────
  const dates = gridData?.dates || [];
  const baseHeaders = [
    { key: 'sno', label: 'S.No', width: 6 },
    { key: 'code', label: 'Emp ID', width: 12 },
    { key: 'name', label: 'Employee Name', width: 26 },
    { key: 'role', label: 'Role', width: 14 },
    { key: 'labourType', label: 'Labour Type', width: 16 },
    { key: 'batch', label: 'Batch', width: 16 },
    { key: 'category', label: 'Category', width: 14 },
    { key: 'shift', label: 'Shift', width: 12 },
  ];

  const dateHeaders = dates.map((d) => {
    const dateStr = toDateStr(d);
    const parts = dateStr.split('-');
    const shortDate = parts.length === 3 ? `${parts[2]}/${parts[1]}` : dateStr;
    const dow = (typeof d === 'object' && d?.weekday) ? String(d.weekday).toUpperCase() : dayOfWeekName(dateStr);
    return {
      key: `date_${dateStr}`,
      label: dow ? `${shortDate}\n${dow}` : shortDate,
      dateStr,
      width: 10,
    };
  });

  const summaryHeaders = [
    { key: 'present', label: 'Present\n(P)', width: 9 },
    { key: 'halfDay', label: 'Half Day\n(HD)', width: 9 },
    { key: 'absent', label: 'Absent\n(A)', width: 9 },
    { key: 'totalDays', label: 'Paid\nDays', width: 9 },
    { key: 'totalHours', label: 'Total\nHours', width: 10 },
    { key: 'dayRate', label: 'Day Rate\n(₹)', width: 11 },
    { key: 'totalEarned', label: 'Total\nAmount (₹)', width: 13 },
  ];

  const allColumns = [...baseHeaders, ...dateHeaders, ...summaryHeaders];
  const headerRowIdx = 8;
  const headerRow = ws.getRow(headerRowIdx);
  headerRow.height = 32;

  allColumns.forEach((col, idx) => {
    const cell = headerRow.getCell(idx + 1);
    cell.value = col.label;
    cell.font = { bold: true, size: 9, color: { argb: 'FFFFFFFF' } };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: idx < baseHeaders.length ? 'FF1E293B' : idx < baseHeaders.length + dateHeaders.length ? 'FF334155' : 'FF0F172A' },
    };
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
    cell.border = {
      top: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      left: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      bottom: { style: 'medium', color: { argb: 'FF94A3B8' } },
      right: { style: 'thin', color: { argb: 'FFCBD5E1' } },
    };
  });

  // ─── 3. Data Rows ───────────────────────────────────────────────────
  const employees = gridData?.employees || [];
  let currentRowIdx = headerRowIdx + 1;

  let grandTotalPresent = 0;
  let grandTotalHalf = 0;
  let grandTotalAbsent = 0;
  let grandTotalDays = 0;
  let grandTotalHours = 0;
  let grandTotalAmount = 0;

  for (let i = 0; i < employees.length; i += 1) {
    const emp = employees[i];
    const row = ws.getRow(currentRowIdx);
    row.height = 20;

    const selections = emp.selections || [];
    const getSel = (label) => selections.find((s) => s.label?.toLowerCase() === label.toLowerCase())?.value || '—';

    const labourTypeVal = getSel('Labour Type');
    const batchVal = getSel('Batch');
    const categoryVal = getSel('Work Category');
    const shiftVal = (emp.days || []).find((d) => d.shiftName)?.shiftName || '—';

    // Base info
    row.getCell(1).value = i + 1;
    row.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };

    row.getCell(2).value = emp.registrationCode || '—';
    row.getCell(2).alignment = { horizontal: 'center', vertical: 'middle' };
    row.getCell(2).font = { bold: true, size: 9 };

    row.getCell(3).value = emp.displayName || '—';
    row.getCell(3).alignment = { horizontal: 'left', vertical: 'middle' };
    row.getCell(3).font = { bold: true, size: 9 };

    row.getCell(4).value = emp.roleName || '—';
    row.getCell(4).alignment = { horizontal: 'center', vertical: 'middle' };

    row.getCell(5).value = labourTypeVal;
    row.getCell(5).alignment = { horizontal: 'center', vertical: 'middle' };

    row.getCell(6).value = batchVal;
    row.getCell(6).alignment = { horizontal: 'center', vertical: 'middle' };

    row.getCell(7).value = categoryVal;
    row.getCell(7).alignment = { horizontal: 'center', vertical: 'middle' };

    row.getCell(8).value = shiftVal;
    row.getCell(8).alignment = { horizontal: 'center', vertical: 'middle' };

    for (let c = 1; c <= 8; c += 1) {
      row.getCell(c).border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
      };
      if (c !== 2 && c !== 3) row.getCell(c).font = { size: 9 };
    }

    // Days mapping
    const dayMap = new Map((emp.days || []).map((d) => [toDateStr(d?.date || d), d]));

    dateHeaders.forEach((dh, dIdx) => {
      const colIdx = baseHeaders.length + dIdx + 1;
      const cell = row.getCell(colIdx);
      const day = dayMap.get(dh.dateStr);

      const cellText = getAttendanceCode(day);
      cell.value = cellText;
      cell.alignment = { horizontal: 'center', vertical: 'middle' };

      if (cellText === '—') {
        cell.font = { color: { argb: 'FF94A3B8' }, size: 8 };
      } else if (cellText === 'P') {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDCFCE7' } };
        cell.font = { size: 8, bold: true, color: { argb: 'FF166534' } };
      } else if (cellText === '1.5S' || cellText === 'DS') {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDBEAFE' } };
        cell.font = { size: 8, bold: true, color: { argb: 'FF1E40AF' } };
      } else if (cellText === 'HD' || cellText === 'FH' || cellText === 'SH' || cellText === 'PT') {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEF3C7' } };
        cell.font = { size: 8, bold: true, color: { argb: 'FF92400E' } };
      } else if (cellText === 'A') {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEE2E2' } };
        cell.font = { size: 8, bold: true, color: { argb: 'FF991B1B' } };
      } else {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDCFCE7' } };
        cell.font = { size: 8, bold: true, color: { argb: 'FF166534' } };
      }

      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
      };
    });

    const empPresent = emp.summary?.present ?? 0;
    const empHalf = emp.summary?.halfDay ?? 0;
    const empAbsent = emp.summary?.absent ?? 0;
    const empPaidDays = emp.payment?.paymentDays != null ? Number(emp.payment.paymentDays) : (emp.summary?.totalDays ?? 0);
    const empHours = (emp.days || []).reduce((acc, d) => acc + (Number(d.activityHours) || 0), 0);
    const rate = Number(emp.payAmount) || 0;
    const earned = emp.payment?.totalAmount != null ? Number(emp.payment.totalAmount) : Math.round(rate * empPaidDays * 100) / 100;

    grandTotalPresent += empPresent;
    grandTotalHalf += empHalf;
    grandTotalAbsent += empAbsent;
    grandTotalDays += empPaidDays;
    grandTotalHours += empHours;
    grandTotalAmount += earned;

    const summaryStartCol = baseHeaders.length + dateHeaders.length + 1;
    const summaryVals = [
      empPresent,
      empHalf,
      empAbsent,
      Math.round(empPaidDays * 10) / 10,
      Math.round(empHours * 10) / 10,
      rate,
      earned,
    ];

    summaryVals.forEach((val, sIdx) => {
      const cell = row.getCell(summaryStartCol + sIdx);
      cell.value = val;
      cell.alignment = { horizontal: sIdx >= 5 ? 'right' : 'center', vertical: 'middle' };
      cell.font = { size: 9, bold: sIdx === 3 || sIdx === 6 };
      if (sIdx >= 5) cell.numFmt = '#,##0.00';
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
      };
    });

    currentRowIdx += 1;
  }

  // ─── 4. Grand Total Row ─────────────────────────────────────────────
  const totalRow = ws.getRow(currentRowIdx);
  totalRow.height = 24;
  totalRow.getCell(1).value = 'TOTAL';
  totalRow.getCell(1).font = { bold: true, size: 10 };
  totalRow.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };
  ws.mergeCells(`A${currentRowIdx}:H${currentRowIdx}`);

  for (let c = 1; c <= allColumns.length; c += 1) {
    const cell = totalRow.getCell(c);
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
    cell.border = {
      top: { style: 'medium', color: { argb: 'FF94A3B8' } },
      bottom: { style: 'double', color: { argb: 'FF475569' } },
      left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
      right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
    };
  }

  const summaryStartCol = baseHeaders.length + dateHeaders.length + 1;
  const totals = [
    grandTotalPresent,
    grandTotalHalf,
    grandTotalAbsent,
    Math.round(grandTotalDays * 10) / 10,
    Math.round(grandTotalHours * 10) / 10,
    '',
    grandTotalAmount,
  ];

  totals.forEach((val, sIdx) => {
    const cell = totalRow.getCell(summaryStartCol + sIdx);
    cell.value = val;
    cell.font = { bold: true, size: 10, color: { argb: 'FF0F172A' } };
    cell.alignment = { horizontal: sIdx >= 5 ? 'right' : 'center', vertical: 'middle' };
    if (sIdx === 6) cell.numFmt = '₹#,##0.00';
  });

  // ─── 5. Set Column Widths ───────────────────────────────────────────
  allColumns.forEach((col, idx) => {
    ws.getColumn(idx + 1).width = col.width;
  });

  // ─── 6. Write Buffer & Trigger Download ─────────────────────────────
  const buffer = await wb.xlsx.writeBuffer();
  const filename = `Attendance_History_${safeFilename(roleName || 'All')}_${safeFilename(dateFrom)}_to_${safeFilename(dateTo)}.xlsx`;
  triggerBlobDownload(
    new Blob([buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    }),
    filename
  );
}
