const IST_TIMEZONE = 'Asia/Kolkata';
const SLIPS_PER_PAGE = 5;

function parsePdfDateValue(value) {
  if (value instanceof Date) return value;
  if (typeof value === 'string') {
    const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
    if (match) {
      return new Date(`${match[1]}-${match[2]}-${match[3]}T12:00:00+05:30`);
    }
  }
  return new Date(value);
}

function formatSlipDate(value) {
  if (!value) return '—';
  const d = value instanceof Date ? value : parsePdfDateValue(value);
  if (Number.isNaN(d.getTime())) return '—';
  return d.toLocaleDateString('en-GB', {
    timeZone: IST_TIMEZONE,
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  }).replace(/\//g, '-');
}

function formatDays(value) {
  const n = Number(value);
  if (!Number.isFinite(n)) return '0';
  return Number.isInteger(n) ? String(n) : String(Math.round(n * 100) / 100);
}

function formatNetAmount(amount) {
  const n = Number(amount);
  if (!Number.isFinite(n)) return '0';
  if (Number.isInteger(n) || Math.abs(n - Math.round(n)) < 0.005) {
    return String(Math.round(n));
  }
  return n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function fitText(doc, text, maxWidth) {
  const value = String(text || '—');
  if (doc.getTextWidth(value) <= maxWidth) return value;
  let trimmed = value;
  while (trimmed.length > 1 && doc.getTextWidth(`${trimmed}…`) > maxWidth) {
    trimmed = trimmed.slice(0, -1);
  }
  return `${trimmed}…`;
}

function cellText(doc, text, x, y, w, h, { bold = false, size = 10, align = 'left' } = {}) {
  const pad = 6;
  doc.setFont('helvetica', bold ? 'bold' : 'normal');
  doc.setFontSize(size);
  doc.setTextColor(0, 0, 0);
  const maxWidth = Math.max(8, w - pad * 2);
  const drawn = fitText(doc, text, maxWidth);
  const textH = size * 0.72;
  const textY = y + h / 2 + textH / 2 - 1;
  if (align === 'right') {
    doc.text(drawn, x + w - pad, textY, { align: 'right' });
    return;
  }
  if (align === 'center') {
    doc.text(drawn, x + w / 2, textY, { align: 'center' });
    return;
  }
  doc.text(drawn, x + pad, textY);
}

function drawWatermark(doc, x, y, w, h) {
  const label = 'SYSTEM GENERATED BY SAMS';
  const canStack = typeof doc.saveGraphicsState === 'function' && typeof doc.restoreGraphicsState === 'function';
  if (canStack) doc.saveGraphicsState();
  try {
    if (typeof doc.GState === 'function') {
      doc.setGState(new doc.GState({ opacity: 0.18 }));
    }
  } catch {
    // Older jsPDF builds still render a light watermark without opacity.
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(Math.max(11, Math.min(15, w / 22)));
  doc.setTextColor(168, 174, 184);
  doc.text(label, x + w / 2, y + h / 2 + 2, {
    align: 'center',
    angle: 16,
  });
  if (canStack) doc.restoreGraphicsState();
  doc.setTextColor(0, 0, 0);
}

function drawCompactSlip(doc, x, y, w, h, details) {
  const slip = details.paySlip || {};
  const labourer = details.labourer || {};
  const period = `Dt ${formatSlipDate(slip.fromDate)} TO ${formatSlipDate(slip.toDate)}`;
  const days = formatDays(details.paymentDays ?? details.summary?.present ?? 0);
  const rows = 4;
  const rowH = h / rows;
  const c1 = w * 0.20;
  const c2 = w * 0.37;
  const c3 = w * 0.20;
  const c4 = w - c1 - c2 - c3;
  const nameWidth = w - c1;
  const dateW = Math.min(210, nameWidth * 0.42);
  const nameValueW = nameWidth - dateW;

  drawWatermark(doc, x, y, w, h);

  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.9);
  doc.rect(x, y, w, h);
  for (let i = 1; i < rows; i += 1) {
    doc.line(x, y + rowH * i, x + w, y + rowH * i);
  }
  doc.line(x + c1, y, x + c1, y + h);
  doc.line(x + c1 + c2, y + rowH, x + c1 + c2, y + h);
  doc.line(x + c1 + c2 + c3, y + rowH, x + c1 + c2 + c3, y + h);

  cellText(doc, 'NAME', x, y, c1, rowH, { size: 9 });
  cellText(doc, labourer.name || '—', x + c1, y, nameValueW, rowH, { bold: true, size: 12 });
  cellText(doc, period, x + c1 + nameValueW, y, dateW, rowH, { bold: true, size: 9, align: 'right' });

  cellText(doc, 'LABOUR TYPE', x, y + rowH, c1, rowH, { size: 8.5 });
  cellText(doc, labourer.labourType || '—', x + c1, y + rowH, c2, rowH, { bold: true, size: 10 });
  cellText(doc, 'B.C.NO.', x + c1 + c2, y + rowH, c3, rowH, { size: 9 });
  cellText(doc, labourer.code || '—', x + c1 + c2 + c3, y + rowH, c4, rowH, { bold: true, size: 11 });

  cellText(doc, 'BATCH', x, y + rowH * 2, c1, rowH, { size: 9 });
  cellText(doc, labourer.batchName || '—', x + c1, y + rowH * 2, c2, rowH, { bold: true, size: 10 });
  cellText(doc, 'WORK CATEGORY', x + c1 + c2, y + rowH * 2, c3, rowH, { size: 8 });
  cellText(doc, labourer.workCategory || '—', x + c1 + c2 + c3, y + rowH * 2, c4, rowH, { bold: true, size: 10 });

  cellText(doc, 'DAYS', x, y + rowH * 3, c1, rowH, { size: 9 });
  cellText(doc, days, x + c1, y + rowH * 3, c2, rowH, { bold: true, size: 11 });
  cellText(doc, 'NET AMOUNT', x + c1 + c2, y + rowH * 3, c3, rowH, { size: 9 });
  cellText(doc, formatNetAmount(slip.amount), x + c1 + c2 + c3, y + rowH * 3, c4, rowH, { bold: true, size: 12 });
}

/**
 * Print compact pay slips — 5 slips per A4 page, matching the mill slip layout.
 */
export async function downloadPaySlipsPdf(detailsList = [], options = {}) {
  const list = (Array.isArray(detailsList) ? detailsList : []).filter(Boolean);
  if (!list.length) {
    throw new Error('Select at least one person to print.');
  }

  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 28;
  const marginY = 22;
  const gap = 10;
  const slipWidth = pageWidth - marginX * 2;
  const usableHeight = pageHeight - marginY * 2;
  const slipHeight = (usableHeight - gap * (SLIPS_PER_PAGE - 1)) / SLIPS_PER_PAGE;

  list.forEach((details, index) => {
    const slot = index % SLIPS_PER_PAGE;
    if (index > 0 && slot === 0) doc.addPage();
    const y = marginY + slot * (slipHeight + gap);
    drawCompactSlip(doc, marginX, y, slipWidth, slipHeight, details);
  });

  const first = list[0]?.paySlip || {};
  const from = first.fromDate || options.dateFrom || 'period';
  const to = first.toDate || options.dateTo || '';
  const filename = to
    ? `pay-slips-${from}-to-${to}.pdf`
    : `pay-slips-${from}.pdf`;
  doc.save(filename);
}
