import { formatDate, formatDateTime, todayDateStringIst } from '@/lib/formatDate';

function cell(value) {
  if (value == null || value === '') return '';
  if (typeof value === 'object') return '';
  return value;
}

function fmtWhen(value) {
  if (!value) return '';
  try {
    return formatDateTime(value);
  } catch {
    return String(value);
  }
}

function downloadBlob(filename, content, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function safeName(value) {
  return String(value || 'labour')
    .replace(/[^\w\-]+/g, '_')
    .slice(0, 40);
}

/**
 * Professional Excel for a single labour × project assignment period.
 */
export async function downloadLabourAssignmentExcel(report, { generatedBy } = {}) {
  const ExcelJS = (await import('exceljs')).default;
  const data = report?.data || report || {};
  const header = data.header || {};
  const labour = header.labour || data.overview?.labour || {};
  const project = header.project || data.overview?.project || {};
  const assignment = data.projectAssignment || header.assignment || {};
  const summary = data.summary || {};
  const stamp = todayDateStringIst();

  const wb = new ExcelJS.Workbook();
  wb.creator = 'SAMS';
  wb.created = new Date();

  const summarySheet = wb.addWorksheet('Summary');
  summarySheet.mergeCells('A1:B1');
  summarySheet.getCell('A1').value = 'SAMS — Project Labour Report';
  summarySheet.getCell('A1').font = { bold: true, size: 16, color: { argb: 'FF1E405F' } };
  summarySheet.getCell('A2').value = 'Smart Access Management System';
  summarySheet.getCell('A2').font = { italic: true, color: { argb: 'FF64748B' } };

  const infoRows = [
    ['Report Generated Date', stamp],
    ['Generated By', generatedBy || '—'],
    [],
    ['Labour Information'],
    ['Labour Name', labour.labourName],
    ['Labour ID', labour.registrationCode],
    ['Role', labour.roleName],
    [],
    ['Project Information'],
    ['Project Name', project.projectName],
    ['Project Status', project.statusLabel || project.status],
    ['Project Type', project.projectTypeLabel || project.projectType],
    ['Department', project.department?.name || header.departmentName],
    ['Division', project.division?.name || header.divisionName],
    [],
    ['Assignment Information'],
    ['Assigned Date', fmtWhen(assignment.assignedAt)],
    ['Assigned By', assignment.assignedBy],
    ['Removed Date', fmtWhen(assignment.removedAt)],
    ['Period From', assignment.periodFrom],
    ['Period To', assignment.removedAt ? assignment.periodTo : 'Present'],
    ['Assignment Status', assignment.status],
    [],
    ['Attendance Summary'],
    ['Days Worked', summary.daysWorked],
    ['Assignment Window Days', summary.windowDays],
    ['Attendance Percentage', summary.attendancePercentage != null ? `${summary.attendancePercentage}%` : ''],
    ['Total Worked Hours', summary.totalWorkedHours],
    ['Average Working Hours', summary.averageWorkingHours],
  ];

  let rowIdx = 4;
  for (const row of infoRows) {
    if (!row.length) {
      rowIdx += 1;
      continue;
    }
    if (row.length === 1) {
      summarySheet.getCell(`A${rowIdx}`).value = row[0];
      summarySheet.getCell(`A${rowIdx}`).font = { bold: true, size: 12 };
    } else {
      summarySheet.getCell(`A${rowIdx}`).value = row[0];
      summarySheet.getCell(`B${rowIdx}`).value = cell(row[1]);
    }
    rowIdx += 1;
  }
  summarySheet.getColumn(1).width = 28;
  summarySheet.getColumn(2).width = 36;

  const attSheet = wb.addWorksheet('Daily Attendance');
  attSheet.addRow(['Date', 'Entry Time', 'Exit Time', 'Worked Hours', 'Attendance Status']);
  attSheet.getRow(1).font = { bold: true };
  for (const r of data.attendanceHistory || []) {
    attSheet.addRow([
      r.date,
      fmtWhen(r.entryTime),
      fmtWhen(r.exitTime),
      r.workedHours ?? '',
      r.attendanceStatus || r.status || '',
    ]);
  }
  attSheet.columns.forEach((col) => {
    col.width = 18;
  });

  const gateSheet = wb.addWorksheet('Gate Activity');
  gateSheet.addRow(['Date', 'Gate', 'Entry', 'Exit', 'Operator', 'Remarks']);
  gateSheet.getRow(1).font = { bold: true };
  for (const r of data.gateActivity || []) {
    gateSheet.addRow([
      r.date,
      r.gate || '',
      fmtWhen(r.entry),
      fmtWhen(r.exit),
      r.operator || '',
      r.remarks || '',
    ]);
  }
  gateSheet.columns.forEach((col) => {
    col.width = 18;
  });

  const faceSheet = wb.addWorksheet('Face Captures');
  faceSheet.addRow([
    'Date',
    'Capture Time',
    'Camera',
    'Verification',
    'Similarity Score',
    'Entry Verified',
    'Exit Verified',
  ]);
  faceSheet.getRow(1).font = { bold: true };
  for (const r of data.faceCaptureRecords || []) {
    faceSheet.addRow([
      r.date,
      fmtWhen(r.captureTime),
      r.camera || '',
      r.verificationStatus || '',
      r.similarityScore ?? '',
      r.entryCapture?.verified ? 'Yes' : r.entryCapture ? 'No' : '',
      r.exitCapture?.verified ? 'Yes' : r.exitCapture ? 'No' : '',
    ]);
  }
  faceSheet.columns.forEach((col) => {
    col.width = 16;
  });

  const buffer = await wb.xlsx.writeBuffer();
  const name = `SAMS_Project_Labour_${safeName(labour.registrationCode || labour.labourName)}_${stamp}.xlsx`;
  downloadBlob(
    name,
    buffer,
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  );
}

/**
 * Professional PDF for a single labour × project assignment period.
 */
export async function downloadLabourAssignmentPdf(report, { generatedBy } = {}) {
  const [{ jsPDF }, autoTableModule] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);
  const autoTable = autoTableModule.default;
  const data = report?.data || report || {};
  const header = data.header || {};
  const labour = header.labour || {};
  const project = header.project || {};
  const assignment = data.projectAssignment || header.assignment || {};
  const summary = data.summary || {};
  const stamp = todayDateStringIst();

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const margin = 14;
  let y = 16;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(30, 64, 95);
  doc.text('SAMS', margin, y);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text('Smart Access Management System', margin + 18, y);
  y += 8;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text('Project Labour Report', margin, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated ${stamp}${generatedBy ? ` · By ${generatedBy}` : ''}`, margin, y);
  y += 8;

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, 210 - margin, y);
  y += 6;

  const detailRows = [
    ['Labour Name', labour.labourName || '—'],
    ['Labour ID', labour.registrationCode || '—'],
    ['Project', project.projectName || '—'],
    ['Department', project.department?.name || header.departmentName || '—'],
    ['Division', project.division?.name || header.divisionName || '—'],
    ['Assigned', formatDate(assignment.assignedAt) || '—'],
    ['Assigned By', assignment.assignedBy || '—'],
    [
      'Assignment Period',
      `${assignment.periodFrom || '—'} → ${assignment.removedAt ? assignment.periodTo : 'Present'}`,
    ],
    ['Status', assignment.status || '—'],
    ['Days Worked', String(summary.daysWorked ?? '—')],
    ['Attendance %', summary.attendancePercentage != null ? `${summary.attendancePercentage}%` : '—'],
    ['Total Hours', String(summary.totalWorkedHours ?? '—')],
  ];

  autoTable(doc, {
    startY: y,
    head: [['Field', 'Value']],
    body: detailRows,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [30, 64, 95] },
    margin: { left: margin, right: margin },
  });

  y = doc.lastAutoTable.finalY + 8;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('Daily Attendance', margin, y);

  autoTable(doc, {
    startY: y + 2,
    head: [['Date', 'Entry', 'Exit', 'Hours', 'Status']],
    body: (data.attendanceHistory || []).map((r) => [
      r.date || '',
      r.entryTime ? formatDateTime(r.entryTime) : '',
      r.exitTime ? formatDateTime(r.exitTime) : '',
      r.workedHours ?? '',
      r.attendanceStatus || r.status || '',
    ]),
    styles: { fontSize: 7.5, cellPadding: 1.5 },
    headStyles: { fillColor: [30, 64, 95] },
    margin: { left: margin, right: margin },
  });

  doc.addPage();
  y = 16;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Gate Activity', margin, y);
  autoTable(doc, {
    startY: y + 2,
    head: [['Date', 'Gate', 'Entry', 'Exit', 'Operator', 'Remarks']],
    body: (data.gateActivity || []).map((r) => [
      r.date || '',
      r.gate || '',
      r.entry ? formatDateTime(r.entry) : '',
      r.exit ? formatDateTime(r.exit) : '',
      r.operator || '',
      r.remarks || '',
    ]),
    styles: { fontSize: 7.5, cellPadding: 1.5 },
    headStyles: { fillColor: [30, 64, 95] },
    margin: { left: margin, right: margin },
  });

  y = doc.lastAutoTable.finalY + 8;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Face Capture Summary', margin, y);
  autoTable(doc, {
    startY: y + 2,
    head: [['Date', 'Camera', 'Verification', 'Score', 'Capture Time']],
    body: (data.faceCaptureRecords || []).map((r) => [
      r.date || '',
      r.camera || '',
      r.verificationStatus || '',
      r.similarityScore ?? '',
      r.captureTime ? formatDateTime(r.captureTime) : '',
    ]),
    styles: { fontSize: 7.5, cellPadding: 1.5 },
    headStyles: { fillColor: [30, 64, 95] },
    margin: { left: margin, right: margin },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `SAMS Project Labour Report · ${labour.labourName || ''} · Page ${i} of ${pageCount}`,
      margin,
      287
    );
  }

  const name = `SAMS_Project_Labour_${safeName(labour.registrationCode || labour.labourName)}_${stamp}.pdf`;
  doc.save(name);
}
